export const cardStatic = {
  items: [
    {
      id: 2,
      orderNo: "AAAA-1231",
      position: 1,
      clientName: "Капаль Иванович",
      address: "г.Москва, ул.Строителей, д.13, кв.42",
      isDelivered: false,
    },
    {
      id: 4,
      orderNo: "AAAA-1231",
      position: 2,
      clientName: "Непетров Петр",
      address: "г.Москва, ул.Ломателей, д.9, кв.12",
      isDelivered: false,
    },
    {
      id: 5,
      orderNo: "AAAA-1231",
      position: 3,
      clientName: "Сидоров А.",
      address: "г.Москва, ул.Васина, д.13",
      isDelivered: false,
    },
    {
      id: 7,
      orderNo: "AAAA-1231",
      position: 4,
      clientName: "Юрий Иванович",
      address: "г.Москва, ул.Не твоя, д.0",
      isDelivered: false,
    },
    {
      id: 6,
      orderNo: "AAAA-1235",
      position: 5,
      clientName: "Иванов Иван",
      address: "г.Москва, ул.Строителей, д.15, кв.62",
      isDelivered: false,
    },
    {
      id: 8,
      orderNo: "AAAA-1235",
      position: 6,
      clientName: "Непетров Петр",
      address: "г.Москва, ул.Ломателей, д.11, кв.32",
      isDelivered: false,
    },
    {
      id: 9,
      orderNo: "AAAA-1235",
      position: 7,
      clientName: "Сидоров А.",
      address: "г.Москва, ул.Васина, д.15",
      isDelivered: false,
    },
    {
      id: 11,
      orderNo: "AAAA-1235",
      position: 8,
      clientName: "Юрий Иванович",
      address: "г.Москва, ул.Не твоя, д.2",
      isDelivered: false,
    },
    {
      id: 10,
      orderNo: "AAAA-1239",
      position: 9,
      clientName: "Иванов Иван",
      address: "г.Москва, ул.Строителей, д.17, кв.82",
      isDelivered: false,
    },
    {
      id: 12,
      orderNo: "AAAA-1239",
      position: 10,
      clientName: "Непетров Петр",
      address: "г.Москва, ул.Ломателей, д.13, кв.52",
      isDelivered: false,
    },
    {
      id: 13,
      orderNo: "AAAA-1239",
      position: 11,
      clientName: "Сидоров А.",
      address: "г.Москва, ул.Васина, д.17",
      isDelivered: false,
    },
    {
      id: 15,
      orderNo: "AAAA-1239",
      position: 12,
      clientName: "Юрий Иванович",
      address: "г.Москва, ул.Не твоя, д.4",
      isDelivered: false,
    },
    {
      id: 14,
      orderNo: "AAAA-12313",
      position: 13,
      clientName: "Иванов Иван",
      address: "г.Москва, ул.Строителей, д.19, кв.102",
      isDelivered: false,
    },
    {
      id: 16,
      orderNo: "AAAA-12313",
      position: 14,
      clientName: "Непетров Петр",
      address: "г.Москва, ул.Ломателей, д.15, кв.72",
      isDelivered: false,
    },
    {
      id: 17,
      orderNo: "AAAA-12313",
      position: 15,
      clientName: "Сидоров А.",
      address: "г.Москва, ул.Васина, д.19",
      isDelivered: false,
    },
    {
      id: 19,
      orderNo: "AAAA-12313",
      position: 16,
      clientName: "Юрий Иванович",
      address: "г.Москва, ул.Не твоя, д.6",
      isDelivered: false,
    },
    {
      id: 18,
      orderNo: "AAAA-12317",
      position: 17,
      clientName: "Иванов Иван",
      address: "г.Москва, ул.Строителей, д.21, кв.122",
      isDelivered: false,
    },
    {
      id: 20,
      orderNo: "AAAA-12317",
      position: 18,
      clientName: "Непетров Петр",
      address: "г.Москва, ул.Ломателей, д.17, кв.92",
      isDelivered: false,
    },
    {
      id: 21,
      orderNo: "AAAA-12317",
      position: 19,
      clientName: "Сидоров А.",
      address: "г.Москва, ул.Васина, д.21",
      isDelivered: false,
    },
    {
      id: 23,
      orderNo: "AAAA-12317",
      position: 20,
      clientName: "Юрий Иванович",
      address: "г.Москва, ул.Не твоя, д.8",
      isDelivered: false,
    },
    {
      id: 22,
      orderNo: "AAAA-12321",
      position: 21,
      clientName: "Иванов Иван",
      address: "г.Москва, ул.Строителей, д.23, кв.142",
      isDelivered: false,
    },
    {
      id: 24,
      orderNo: "AAAA-12321",
      position: 22,
      clientName: "Непетров Петр",
      address: "г.Москва, ул.Ломателей, д.19, кв.112",
      isDelivered: false,
    },
    {
      id: 25,
      orderNo: "AAAA-12321",
      position: 23,
      clientName: "Сидоров А.",
      address: "г.Москва, ул.Васина, д.23",
      isDelivered: true,
    },
    {
      id: 27,
      orderNo: "AAAA-12321",
      position: 24,
      clientName: "Юрий Иванович",
      address: "г.Москва, ул.Не твоя, д.10",
      isDelivered: false,
    }
  ],
  get total () {
    return this.items.length;
  }
};

export const sortList = [
  {
    name: "Нет",
    sortProperty: false,
  },
  {
    name: "Только активные",
    sortProperty: true,
  },
];
